### ISSUE TITLE
Add maintainer

### ISSUE THREAD

**Issue by xl0** [conda-forge/lovely-tensors-feedstock#2]
### Comment:

Haha, finally it's in!

Please add me as a maintainer.

**Comment by xl0** [comment]
@sugatoray , ping

**Comment by sugatoray** [comment]
@xl0 Thank you and wishing you a very happy new year. Please do `@mention` me in the comments. This sends a notification to me. 

So, let's do it like this:

1. Please fork the repository and update the recipe for the latest version. And send a PR. Make sure to add yourself to the list of maintainers. 

2. I will review the PR and merge it. Once merged, you will become a co-maintainer. 

This will show you how someone, even though not a maintainer, can update a recipe. Typically I name the updating PRs as "Update `vX.Y.Z`". The sending the PR part is similar to what you will do even if you were a maintainer. 

> Please feel free to ask me questions, if you have any.

**Comment by sugatoray** [comment]
@xl0 Now you are a maintainer as well. And you know the whole process! 
Glad to have you on-board. :)

**Comment by sugatoray** [comment]
Added with #3.
